name: Create Release on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Check if PR is merged
        id: pr_merged
        run: echo "::set-output name=IS_MERGED::$(jq -r .pull_request.merged $GITHUB_EVENT_PATH)"

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          TAG=$(git ls-remote --tags origin | awk -F/ '{print $3}' | sort -V | tail -n 1)
          echo "::set-output name=TAG::$TAG"

      - name: Create GitHub Release
        if: steps.pr_merged.outputs.IS_MERGED == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_latest_tag.outputs.TAG }}
          release_name: Release ${{ steps.get_latest_tag.outputs.TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
